package com.bobbyesp.piped_lib.domain.model.stream

import kotlinx.serialization.Serializable

@Serializable
data class Subtitle(
    val url: String,
    val mimeType: String,
    val name: String,
    val code: String,
    val autogenerated: Boolean,
)
