name: Bug Report
description: Create a report to help us improve
labels: [bug]
body:


  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: |
        Carefully read and work through this check list in order to prevent the most common mistakes and misuse of Spowlo/spotDL (note that most of the bugs are caused by the spotDL library and we need to report them in their repo):
      options:
        - label: I've verified that I'm running the latest [**stable version**](https://github.com/BobbyESP/Spowlo/releases/latest/) of Spowlo or any later [**preview versions**](https://github.com/BobbyESP/Spowlo/releases).
          required: true
        - label: I've checked that the YouTube Music is available in my country.
          required: true
        - label: I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.
          required: true

  - type: textarea
    attributes:
      label: Describe the bug
      description:
      placeholder: |
        A clear and concise description of what the bug is.
    validations:
      required: false

  - type: textarea
    attributes:
      label: To Reproduce
      placeholder: |
        Steps to reproduce the behavior:
        1.Go to '...'
        2.Click on '....'
        3.Scroll down to '....'
        4.See error
    validations:
      required: false

  - type: textarea
    attributes:
      label: Error reports
      placeholder: |
        Click on the displayed error below the text box area to copy it.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Screenshots & Screen Records
      placeholder: |
        Screenshots & Screen Records can amp up bug reports.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Device info
      description: |
        Please provide some information of the device you are using.
        You can get the device info by doing these steps:
        1) Open Spowlo
        2) Go to settings
        3) Click on About
        4) Scroll all the way down
        5) Click "Version"
        6) Paste the info below.
      placeholder: |
        App version: x.x.x (XxXxX)
        Device information: Android XX (API XX)
        Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
        spotDL version: X.X.X
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional context
      description:
      placeholder: |
        Add any other context about the problem here.      
